[theme]
primaryColor = "#6399F0"
 
[browser]
gatherUsageStats = false
 
[runner]
fastReruns = true
 
[client]
showErrorDetails = false
toolbarMode = false
showSidebarNavigation = false
 
[server]
headless = true
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = false